### PR TITLE
fix: fix browser support

### LINKED ISSUE #171: ReferenceError in browsers with v3.0.0
Error: "ReferenceError: process is not defined

Repro: https://jsbin.com/sicotarebe/1/edit?html,console

### PR DESCRIPTION
**Pull request by jerome-benoit**
closes #171

### CODE REVIEW

**Comment by dasa** [comment]
Alternative could be to feature detect using something like this:

```ts
  if ((globalThis as any).process?.hrtime?.bigint) {
    //
  }
```

Thanks for the quick fix!

**Comment by jerome-benoit** [comment]
> Alternative could be to feature detect using something like this:

I plan to add the JS runtime as a `Bench` property later on. And also add it to the results object.

**Comment by dasa** [comment]
With v3.0.1 the error is:

> Uncaught TypeError: Cannot read properties of undefined (reading 'versions')

**Comment by jerome-benoit** [comment]
> With v3.0.1 the error is:
> 
> > Uncaught TypeError: Cannot read properties of undefined (reading 'versions')

Fixed in 3.0.3. The linter removed overzealously null condition checks.

**Pull request merged**
