### PR TITLE
fix: use .call for deoptimization

### LINKED ISSUE #46: The first run is significantly faster even if .warmup() is used
I've been comparing the performance of two versions of the same function, and I've noticed that the first one is always significantly faster, possibly due to JIT.

bench.mjs
```javascript
import { Bench } from "tinybench"

(async () => {
    const bench = new Bench()

    for (const [k, v] of Object.entries({
        "a": (i) => i, // The simpler the compared function, the greater the difference in ops/sec.
        "b": (i) => i,
        "c": (i) => i, // Comparing three functions to illustrate that only the first one is fast.
    })) {
        bench.add(k, () => {
            for (let i = 0; i < 1000; i++) {
                v(i)
            }
        })
    }

    await bench.run()
    console.table(bench.table())
})()
```

```shell
$ node bench.mjs
┌─────────┬───────────┬───────────┬────────────────────┬──────────┬─────────┐
│ (index) │ Task Name │  ops/sec  │ Average Time (ns)  │  Margin  │ Samples │
├─────────┼───────────┼───────────┼────────────────────┼──────────┼─────────┤
│    0    │    'a'    │ '847,777' │ 1179.5548020515819 │ '±1.01%' │ 423889  │
│    1    │    'b'    │ '76,335'  │ 13100.02999778449  │ '±0.41%' │  38168  │
│    2    │    'c'    │ '80,586'  │ 12409.009305943227 │ '±0.32%' │  40294  │
└─────────┴───────────┴───────────┴────────────────────┴──────────┴─────────┘
```

I've also tried increasing `time` and using `.warmup()` but it didn't help so much.

```typescript
import { Bench } from "tinybench"

(async () => {
    const bench = new Bench({ time: 5000, warmupTime: 5000, warmupIterations: 100 })

    for (const [k, v] of Object.entries({
        "a": (i) => i,
        "b": (i) => i,
        "c": (i) => i,
    })) {
        bench.add(k, () => {
            for (let i = 0; i < 1000; i++) {
                v(i)
            }
        })
    }

    await bench.warmup()
    await bench.run()
    console.table(bench.table())
})()
```

```shell
$ node bench.mjs
┌─────────┬───────────┬─────────────┬────────────────────┬──────────┬─────────┐
│ (index) │ Task Name │   ops/sec   │ Average Time (ns)  │  Margin  │ Samples │
├─────────┼───────────┼─────────────┼────────────────────┼──────────┼─────────┤
│    0    │    'a'    │ '1,098,539' │ 910.2996506649747  │ '±0.16%' │ 5492697 │
│    1    │    'b'    │  '96,670'   │ 10344.420296798786 │ '±0.33%' │ 483353  │
│    2    │    'c'    │  '94,520'   │ 10579.704557811108 │ '±0.32%' │ 472603  │
└─────────┴───────────┴─────────────┴────────────────────┴──────────┴─────────┘
```

Am I missing something? Or could there be an option to run benchmarks in the sequence of a, b, c, a, b, c, ...?

---
Versions:
- tinybench: 2.5.0
- Node.js: Tested on 16.16.0, 18.11.0, and 20.0.0
- OS: Tested on Ubuntu 22 and RunKit

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #46

I tried using .call and it worked. but warmup should be used for more accurate results.

Without warmup: 
```
┌─────────┬───────────┬─────────────┬───────────────────┬──────────┬─────────┐
│ (index) │ Task Name │   ops/sec   │ Average Time (ns) │  Margin  │ Samples │
├─────────┼───────────┼─────────────┼───────────────────┼──────────┼─────────┤
│    0    │    'a'    │ '1,668,042' │ 599.505261791414  │ '±0.47%' │ 834022  │
│    1    │    'b'    │  '159,201'  │ 6281.348724802289 │ '±0.36%' │  79601  │
│    2    │    'c'    │  '162,881'  │ 6139.414994407295 │ '±0.09%' │  81441  │
└─────────┴───────────┴─────────────┴───────────────────┴──────────┴─────────┘

```

With warmup:
```
┌─────────┬───────────┬───────────┬───────────────────┬──────────┬─────────┐
│ (index) │ Task Name │  ops/sec  │ Average Time (ns) │  Margin  │ Samples │
├─────────┼───────────┼───────────┼───────────────────┼──────────┼─────────┤
│    0    │    'a'    │ '163,825' │ 6104.066796782642 │ '±0.14%' │  81913  │
│    1    │    'b'    │ '164,007' │ 6097.265856596651 │ '±0.09%' │  82004  │
│    2    │    'c'    │ '163,775' │ 6105.922276082101 │ '±0.11%' │  81888  │
└─────────┴───────────┴───────────┴───────────────────┴──────────┴─────────┘
```

### CODE REVIEW

**Comment by kurtextrem** [comment]
> but warmup should be used for more accurate results

Should the readme reflect this too?

**Comment by Aslemammad** [comment]
> Should the readme reflect this too?

Why not? feel free to open a PR in case you're interested.

**Comment by exequielbc** [comment]
hi 👋🏽 I wanted to learn about what deoptimization is and why it is needed but couldn't find any resources with a web search (there is plenty of resources for optimization though haha).
Could anyone please point me to a resource or explain here? 🙂

**Comment by Aslemammad** [comment]
Hey @exequielbc! Happy that you're curious, but tbh it's either I don't remember the reason or I just did it randomly and it worked (by benchmarking different solutions)

Sorry for that answer :)

**Pull request merged**
